# for running in docker compose with prebuilt images

# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required

services:
  vote:
    image: 784065479571.dkr.ecr.us-east-1.amazonaws.com/vote
    depends_on:
      redis:
        condition: service_healthy 
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: 784065479571.dkr.ecr.us-east-1.amazonaws.com/result
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: 784065479571.dkr.ecr.us-east-1.amazonaws.com/worker
    depends_on:
      redis:
        condition: service_healthy 
      db:
        condition: service_healthy 
    networks:
      - back-tier

  redis:
    image: 784065479571.dkr.ecr.us-east-1.amazonaws.com/redis
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"
    networks:
      - back-tier

  db:
    image: 784065479571.dkr.ecr.us-east-1.amazonaws.com/postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
