kind: ClusterConfig
apiVersion: eksctl.io/v1alpha5
metadata:
  name: vote-cluster
  region: us-west-1
  version: "1.27"
nodeGroups:
  - name: vote-ng
    instanceType: t3.medium
    desiredCapacity: 1
    volumeSize: 10
    ssh:
      allow: true
